In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a_float=a.astype('float32')

print(a,a_float)

[1 2 3] [1. 2. 3.]


In [14]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
zero=np.zeros((3,2),dtype='int32')
print(zero)
one=np.ones((3,2),dtype='int32')
print(one)

[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [18]:
b=a.reshape(-1,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
array=np.arange(9).reshape(3,3)
array[0][0]


0

In [21]:
array2=np.array([1,3,0,9])
array2s=np.argsort(array2)
array2s

array([2, 0, 1, 3], dtype=int64)

In [22]:
import sklearn